### ISSUE TITLE
Installation hangs, installs forever

### ISSUE THREAD

**Issue by embeddedpenguin** [viperML/viperML-overlay#7]
Summary

The package doesn't install from the overlay. It just hangs forever with 0% CPU usage
Steps to Reproduce
```
eselect-repository enable viperML-overlay
emerge --sync
add entry to /etc/portage/package.accept for bismuth
emerge -a bismuth
```
Expected behavior

Package should install as expected or fail with some error output
Screenshots

No response
Bismuth version

3.1.1
KDE Plasma version

5.24.5
The platform KWin is running on

X11
Additional context

No response

**Comment by viperML** [comment]
Hello 👋 

I no longer use Gentoo, but the latest workflow run for bismuth seemed to work https://github.com/viperML/viperML-overlay/runs/6045544072?check_suite_focus=true

**Comment by embeddedpenguin** [comment]
> Hello wave
> 
> I no longer use Gentoo, but the latest workflow run for bismuth seemed to work https://github.com/viperML/viperML-overlay/runs/6045544072?check_suite_focus=true

Hello!
Maybe it's on my end, but I'm not sure how to get any information about the installation process hanging. I've added -vvv and --quiet=n but It just hangs forever with no additional information. Do you know of any way for me to get more debugging information from emerge?

**Comment by viperML** [comment]
Do you even get past downloading the source distfiles?

I have to say, that I barely remember how to debug portage's problems.

**Comment by embeddedpenguin** [comment]
It looks like it gets stuck trying to get the distfiles. Stuck on the emerging step, never gets to installing
